DROP TABLE IF EXISTS PRICES;

CREATE TABLE NAVES_ESPACIALES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    MODELO VARCHAR(30) NOT NULL,
    SERIE_PELICULA VARCHAR(50) NOT NULL,
    NUM_TRIPULANTES INT NOT NULL,
    FECHA_LANZAMIENTO TIMESTAMP,
    FABRICANTE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(300)
);